# vvv THOG
from pathlib import Path

path = Path("tmp_premat_processing_tranche.py")
text = path.read_text()
old = '''replace_once(\n    "sheet/trainer_step.py",\n    '            with self.distributed.no_sync_context(self.model, enabled=not should_sync):\\n                with self.autocast_context():\\n',\n    '            with self.distributed.no_sync_context(self.model, enabled=not should_sync):\\n                # vvv THOG capture exactly one first accumulation forward; backward/checkpoint replay remains outside the Nsight range\\n                with processing_capture_scope(\\n                    enabled=(str(getattr(self.config, "premat_processing_logging", "disabled")) == "enabled"),\\n                    completed_updates=self.state.completed_updates,\\n                    max_updates=self.config.max_updates,\\n                    log_interval=self.config.log_interval,\\n                    micro_step=micro_step,\\n                    device=self.device,\\n                ):\\n                    with self.autocast_context():\\n                # ^^^ THOG\\n',\n)\n# The inserted extra nesting requires indenting the existing autocast body until the first post-autocast statement.\ntrainer_path = ROOT / "sheet/trainer_step.py"\ntrainer_text = trainer_path.read_text()\nneedle = '                    with self.autocast_context():\\n                # ^^^ THOG\\n'\nstart = trainer_text.index(needle) + len(needle)\nend_marker = '                total_loss += float(loss.detach().item())\\n'\nend = trainer_text.index(end_marker, start)\nbody = trainer_text[start:end]\nif not body.strip():\n    raise RuntimeError("trainer processing capture insertion found empty autocast body")\nbody = ''.join(('    ' + line if line.strip() else line) for line in body.splitlines(keepends=True))\ntrainer_text = trainer_text[:start] + body + trainer_text[end:]\ntrainer_path.write_text(trainer_text)'''
new = '''replace_once(\n    "sheet/trainer_step.py",\n    '                with self.distributed.no_sync_context(\\n                    self.model,\\n                    synchronize=synchronize,\\n                ):\\n                    with self.autocast_context():\\n',\n    '                with self.distributed.no_sync_context(\\n                    self.model,\\n                    synchronize=synchronize,\\n                ):\\n                    # vvv THOG capture exactly one first accumulation forward; backward/checkpoint replay remains outside the Nsight range\\n                    with processing_capture_scope(\\n                        enabled=(str(getattr(self.config, "premat_processing_logging", "disabled")) == "enabled"),\\n                        completed_updates=self.state.completed_updates,\\n                        max_updates=self.config.max_updates,\\n                        log_interval=self.config.log_interval,\\n                        micro_step=micro_step,\\n                        device=self.device,\\n                    ):\\n                        with self.autocast_context():\\n',\n)\n# The inserted extra nesting requires indenting the existing autocast body until the first post-autocast statement.\ntrainer_path = ROOT / "sheet/trainer_step.py"\ntrainer_text = trainer_path.read_text()\nneedle = '                        with self.autocast_context():\\n'\nstart = trainer_text.index(needle) + len(needle)\nend_marker = '                    total_loss += self.distributed.mean_float(loss.detach())\\n'\nend = trainer_text.index(end_marker, start)\nbody = trainer_text[start:end]\nif not body.strip():\n    raise RuntimeError("trainer processing capture insertion found empty autocast body")\nbody = ''.join(('    ' + line if line.strip() else line) for line in body.splitlines(keepends=True))\ntrainer_text = trainer_text[:start] + body + '                    # ^^^ THOG\\n' + trainer_text[end:]\ntrainer_path.write_text(trainer_text)'''
if text.count(old) != 1:
    raise RuntimeError(f"expected one trainer capture helper block, found {text.count(old)}")
path.write_text(text.replace(old, new, 1))
print("processing helper trainer capture anchor repaired")
# ^^^ THOG
