// vvv THOG exercise History, Downloads, manual Grid colours and individual eye exclusions in the full dashboard
"use strict";
const assert=require("node:assert/strict"),fs=require("node:fs");
const {chromium,firefox}=require("playwright");
const address=process.env.INSTRA_TEST_URL||"http://127.0.0.1:8765";
async function check(type) {
  const browser=await type.launch({headless:true,
    ...(type===firefox && process.env.INSTRA_TEST_UNSANDBOXED==="1" ? {firefoxUserPrefs:{"security.sandbox.content.level":0,"fission.autostart":false,"dom.ipc.processCount":1}} : {}),...(type===chromium && process.env.INSTRA_CHROMIUM_PATH?
    {executablePath:process.env.INSTRA_CHROMIUM_PATH,args:["--no-sandbox","--disable-dev-shm-usage","--use-gl=angle","--use-angle=swiftshader","--enable-unsafe-swiftshader"]}:{})});
  const browser_context=await browser.newContext({viewport:{width:1600,height:1100}});
  const page=await browser_context.newPage();
  const errors=[];page.on("pageerror",error=>{errors.push(error.message);console.log("PAGE ERROR",error.stack);});
  page.on("dialog",dialog=>dialog.dismiss());
  const response=await page.request.get(address+"/api/runner");
  const snapshot=await response.json();
  const diagnostic="A long failure message that should use all available History row space. ".repeat(5)+"END_OF_DIAGNOSTIC";
  snapshot.grids[2].runs[0].attempts=[{attempt_id:"failed",started_at:"2026-09-30T00:01:00Z",finished_at:"2026-09-30T00:02:05Z",exit_code:1,failure_excerpt:diagnostic}];
  await page.route(address+"/api/runner",route=>route.fulfill({json:snapshot}));
  await page.goto(address+"/runs/fixture_00");
  await page.waitForFunction(()=>typeof app!=="undefined"&&app.runs.length===12);
  await page.locator("#runner_nav").click();
  await page.waitForSelector("#runner_detail input[data-runner-field]");
  assert.equal(await page.locator('[data-runner-tab="current_scripts"]').count(),0);
  await page.locator('[data-runner-tab="history"]').click();
  const rows=page.locator(".runner-history-grid-row");
  assert.equal(await rows.count(),4);
  assert.deepEqual(await page.locator(".runner-history-headings span").allTextContents(),["Grid","State","","","start","end","T","T_est",""]);
  const terminal=rows.filter({has:page.locator('button',{hasText:"Grid 1"})});
  assert.equal(await terminal.locator(".runner-history-time").textContent(),"1m 5s");
  assert.equal(await terminal.locator(".runner-history-estimate").textContent(),"1m 0s – 2m 0s");
  const alignment=await rows.evaluateAll(elements=>elements.map(row=>[...row.children].map(child=>child.getBoundingClientRect().left)));
  for(let column=0;column<9;column++)assert.ok(alignment.every(values=>Math.abs(values[column]-alignment[0][column])<1),`History column ${column} misaligned`);
  assert.equal(await terminal.evaluate(row=>row.children[1].classList.contains("runner-status")),true);
  assert.equal(await terminal.evaluate(row=>row.children[2].textContent),"Rename");
  assert.equal(await terminal.locator(".runner-recipe-delete").evaluate(node=>getComputedStyle(node).color),"rgb(179, 38, 46)");
  const failure=rows.filter({has:page.locator('button',{hasText:"Grid 3"})}).locator(".runner-history-error");
  assert.ok((await failure.textContent()).endsWith("END_OF_DIAGNOSTIC"),"failure text was truncated");
  const bounds=await failure.evaluate(node=>({right:node.getBoundingClientRect().right,parent:node.parentElement.getBoundingClientRect().right,width:node.getBoundingClientRect().width}));
  assert.ok(bounds.width>250 && bounds.parent-bounds.right<20,JSON.stringify(bounds));
  await terminal.locator("button").first().click();
  assert.match(await page.locator(".runner-grid-state").textContent(),/4\/4 runs completed/);
  await page.screenshot({path:`/tmp/instra-oct01-${type.name()}-history.png`});
  await page.locator('[data-runner-tab="files"]').click();
  await page.locator('#runner_list > button',{hasText:"Grid 1"}).click();
  const file_rows=page.locator(".runner-download-row");
  assert.equal(await file_rows.count(),7);
  for(const row of await file_rows.all()) {
    const label=await row.locator("span").textContent();
    const view=row.locator("button"),download=row.locator("a");
    const filename=await download.getAttribute("download");
    assert.ok(filename.startsWith("G-00001"),filename);
    await view.click();
    await page.waitForFunction(()=>!document.querySelector('.runner-script-viewer').textContent.includes("Loading…"));
    assert.ok((await page.locator(".runner-file-displayed").textContent()).includes(label));
    assert.equal(await view.getAttribute("aria-pressed"),"true");
    const source=await page.locator(".runner-script-viewer").textContent();
    assert.ok(source.includes("G-00001") && !source.includes("unavailable"),source);
    const fetched=await page.request.get(address+await download.getAttribute("href"));
    assert.equal(fetched.status(),200);
    assert.match(fetched.headers()["content-disposition"],/attachment; filename\*=UTF-8''G-00001/);
    assert.equal(await fetched.text(),source);
    const download_event=page.waitForEvent("download");
    await download.click();
    const downloaded=await download_event;
    assert.equal(downloaded.suggestedFilename(),filename);
    assert.equal(fs.readFileSync(await downloaded.path(),"utf8"),source);
  }
  // A late response for a prior View must never replace the currently selected preview.
  await page.route(/\/api\/runner\/file\?.*name=manifest$/,async route=>{
    await new Promise(resolve=>setTimeout(resolve,450));try{await route.continue();}catch(_){/* aborted obsolete preview */}
  });
  await file_rows.filter({hasText:"Resolved Manifest"}).locator("button").click();
  await file_rows.filter({hasText:"Placement"}).locator("button").click();
  await page.waitForFunction(()=>document.querySelector('.runner-script-viewer').textContent.includes('"file": "placement"'));
  await page.waitForTimeout(600);
  assert.match(await page.locator(".runner-script-viewer").textContent(),/"file": "placement"/);
  await page.waitForTimeout(5100);
  assert.match(await page.locator(".runner-file-displayed").textContent(),/Placement/);
  assert.equal(await file_rows.filter({hasText:"Placement"}).locator("button").getAttribute("aria-pressed"),"true");
  await page.locator('#runner_list > button',{hasText:"Grid 2"}).click();
  await page.waitForFunction(()=>document.querySelector('.runner-script-viewer').textContent.includes("G-00002"));
  await page.locator('#runner_list > button',{hasText:"Grid 1"}).click();
  await page.waitForFunction(()=>document.querySelector('.runner-script-viewer').textContent.includes('"file": "placement"'));
  await page.screenshot({path:`/tmp/instra-oct01-${type.name()}-downloads.png`});
  await page.locator("#runs_nav").click();
  const run_row=id=>page.locator(`#runs_body tr[data-run-id="${id}"]`);
  await page.waitForSelector('#runs_body tr[data-run-id="fixture_00"]');
  assert.equal(await page.locator(".runs-table th.loss-column").textContent(),"loss");
  await run_row("fixture_00").locator(".colour-dot").click();
  await page.waitForSelector("#colour_popover",{state:"visible"});
  await page.locator("#colour_hex").fill("#CC3377");
  await page.locator("#colour_hex").dispatchEvent("change");
  await page.waitForFunction(()=>colour_for_run("fixture_00")==="#CC3377");
  await page.locator("#runs_nav").click();
  await page.evaluate(()=>{for(const run of app.runs)app.visibility[run_identifier(run)]=false;save_json("thog2_local_run_visibility",app.visibility);render_runs();});
  await run_row("fixture_00").locator(".eye-button").click();
  await run_row("fixture_04").locator(".eye-button").click();
  assert.equal(await page.evaluate(()=>app.runs.filter(run=>is_visible(run_identifier(run))).length),8);
  await run_row("fixture_01").locator(".eye-button").click();
  assert.equal(await page.evaluate(()=>app.runs.filter(run=>is_visible(run_identifier(run))).length),7);
  assert.equal(await page.evaluate(()=>is_visible("fixture_00")&&is_visible("fixture_02")&&!is_visible("fixture_01")&&is_visible("fixture_04")),true);
  const menu_button=run_row("fixture_00").locator(".run-menu-button");
  await menu_button.click();
  assert.equal(await page.locator("#delete_grid_runs span").textContent(),await page.locator("#delete_run span").textContent());
  assert.equal(await page.locator("#delete_grid_runs").evaluate(node=>getComputedStyle(node).color),await page.locator("#delete_run").evaluate(node=>getComputedStyle(node).color));
  await page.locator("#workspace_nav").click();
  await page.waitForFunction(()=>document.querySelector('[data-metric-chart-id="train/loss"] .plot-mount')?.data?.length===7,{},{timeout:20000});
  await page.waitForFunction(()=>document.getElementById('training_throughput_plot')?.data?.length===7,{},{timeout:20000});
  assert.equal(await page.evaluate(()=>document.querySelector('[data-metric-chart-id="train/loss"] .plot-mount').data.find(trace=>trace.meta.instra_workspace_run_id==="fixture_00").line.color),"#CC3377");
  for(const id of ["fixture_02","fixture_03"])await run_row(id).locator(".eye-button").click();
  await page.waitForFunction(()=>document.querySelector('[data-metric-chart-id="train/loss"] .plot-mount')?.data?.length===5);
  assert.deepEqual(await page.evaluate(()=>window.__instra_workspace.visible_runs().filter(run=>run.runner_grid_tag==="G-00001").map(run_identifier)),["fixture_00"]);
  await run_row("fixture_00").locator(".eye-button").click();
  await page.waitForFunction(()=>document.querySelector('[data-metric-chart-id="train/loss"] .plot-mount')?.data?.length===4);
  assert.equal(await page.evaluate(()=>document.querySelector('[data-metric-chart-id="train/loss"] .plot-mount').data.some(trace=>trace.meta.instra_workspace_run_id==="fixture_00")),false,"hidden current run retained its curve");
  const saved=await page.evaluate(()=>localStorage.getItem("thog2_local_run_visibility"));
  // A fresh page in the same session must retain both colour and eye choices.
  const second=await page.context().newPage();
  await second.goto(address+"/runs/fixture_00");
  await second.waitForFunction(()=>typeof app!=="undefined"&&app.runs.length===12);
  assert.equal(await second.evaluate(()=>colour_for_run("fixture_00")),"#CC3377");
  assert.equal(await second.evaluate(()=>localStorage.getItem("thog2_local_run_visibility")),saved);
  const narrow=await browser_context.newPage();
  await narrow.setViewportSize({width:900,height:900});
  await narrow.goto(address+"/runs/fixture_00");
  await narrow.locator("#runner_nav").click();await narrow.locator('[data-runner-tab="history"]').click();
  assert.equal(await narrow.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,"History causes page overflow at a narrow viewport");
  await narrow.close();
  await second.close();
  assert.deepEqual(errors,[]);
  await browser.close();console.log("PASS",type.name(),"History alignment/timing/errors, all downloads/headers/races, Grid colours/exclusions and saved choices");
}
(async()=>{for(const name of (process.env.INSTRA_TEST_BROWSERS||"chromium,firefox").split(','))await check({chromium,firefox}[name]);})().catch(error=>{console.error(error);process.exit(1);});
// ^^^ THOG
