# vvv THOG
from .approximation import (
    ProjectionError,
    fit_sampled_sheets,
    is_within_epsilon,
    project_sampled_sheets,
    projection_error,
    reconstruct_sampled_sheets,
)
from .basis import (
    BASIS_VERSION,
    SINGLE_POINT_COORDINATE,
    BasisCache,
    BasisCacheKey,
    BasisOwner,
    basis_sha256,
    build_stabilized_basis,
    chebyshev_first_kind_basis,
    deterministic_reduced_qr,
    estimated_peak_tensor_bytes,
    normalized_coordinates,
    orthonormality_max_error,
)
from .geometry import (
    MATRIX_FAMILY_NAMES,
    FamilyGeometry,
    SheetGeometryConfig,
    derive_row_order,
    family_geometry_map,
    parameter_count_rows,
    total_dense_equivalent_count,
    total_sheet_parameter_count,
    transformer_family_geometries,
)
from .model import ConventionalLayerNorm, SheetGPT, SheetGPTConfig
from .trajectory import (
    FamilyMetadata,
    SheetTrajectory,
    build_family_metadata,
)

__all__ = [
    "BASIS_VERSION",
    "SINGLE_POINT_COORDINATE",
    "BasisCache",
    "BasisCacheKey",
    "BasisOwner",
    "ConventionalLayerNorm",
    "FamilyGeometry",
    "FamilyMetadata",
    "MATRIX_FAMILY_NAMES",
    "ProjectionError",
    "SheetGPT",
    "SheetGPTConfig",
    "SheetGeometryConfig",
    "SheetTrajectory",
    "basis_sha256",
    "build_family_metadata",
    "build_stabilized_basis",
    "chebyshev_first_kind_basis",
    "derive_row_order",
    "deterministic_reduced_qr",
    "estimated_peak_tensor_bytes",
    "family_geometry_map",
    "fit_sampled_sheets",
    "is_within_epsilon",
    "normalized_coordinates",
    "orthonormality_max_error",
    "parameter_count_rows",
    "project_sampled_sheets",
    "projection_error",
    "reconstruct_sampled_sheets",
    "total_dense_equivalent_count",
    "total_sheet_parameter_count",
    "transformer_family_geometries",
]
# ^^^ THOG
